[build]
	command = "npm run build"
	publish = "build"

[dev]
    framework = "svelte-kit"
    targetPort = 3008
    port = 8009

[[redirects]]
    from = "/experiments/fractalSounds"
    to = "/pages/fractalSound.html"
    status = 200
    force = true

[[redirects]]
    from = "/automata/gasomaton"
    to = "/pages/gasomaton.html"
    status = 200
    force = true

[[redirects]]
    from = "/experiments/*"
    to = "/FractalSoundWeb/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/automata/*"
    to = "/LatticeGasWeb/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}